name: fbus_mobile_student
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.4
  flutter_svg: ^0.22.0
  dio: ^4.0.4
  shared_preferences: ^2.0.10
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.8
  hyper_app_settings: ^0.0.1
  jwt_decode: ^0.3.1

  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  google_sign_in: ^5.4.2

  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  flutter_map_location_marker: ^5.0.0+1

  restart_app: ^1.1.0
  syncfusion_flutter_calendar: ^20.3.56
  syncfusion_localizations: ^20.3.56

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - app_settings.json
    - assets/png/
    - assets/png/month/
